services:  
    macelleria-casi:    
         build:      
              context: .   
              dockerfile: Dockerfile    
              ports:     
                   - "3000:3000"   
            